export const LAT = 37.3688;
export const LON = -122.0363;
export const CITY = "Sunnyvale";

export const CITY_COORDS = {
  "Sunnyvale":     { lat: 37.3688, lon: -122.0363 },
  "San Jose":      { lat: 37.3382, lon: -121.8863 },
  "Cupertino":     { lat: 37.3229, lon: -122.0322 },
  "Mountain View": { lat: 37.3861, lon: -122.0839 },
  "Palo Alto":     { lat: 37.4419, lon: -122.1430 },
  "Saratoga":      { lat: 37.2638, lon: -122.0230 },
};

export const TABS = [
  { id: "indoor",  label: "Indoor Activities", color: "#7c3aed" },
  { id: "weekend", label: "Weekend Activities", color: "#10b981" },
  { id: "summer",  label: "Summer Free Fun",    color: "#f59e0b" },
  { id: "paid",    label: "Paid Activities",    color: "#ef4444" },
];

export const HEAT_PINS = {
  Sunnyvale: [
    { name: "Ortega Park",          lat: 37.3785, lon: -122.0258, type: "park" },
    { name: "Seven Seas Park",       lat: 37.3721, lon: -122.0381, type: "splash" },
    { name: "Sunnyvale Library",     lat: 37.3710, lon: -122.0414, type: "library" },
    { name: "Baylands Park",         lat: 37.4085, lon: -122.0073, type: "park" },
    { name: "Las Palmas Splash Pad", lat: 37.3590, lon: -122.0196, type: "splash" },
    { name: "Pump It Up",            lat: 37.3827, lon: -122.0295, type: "indoor" },
    { name: "Community Center",      lat: 37.3758, lon: -122.0446, type: "indoor" },
    { name: "Murphy Park",           lat: 37.3654, lon: -122.0261, type: "park" },
  ],
  "San Jose": [
    { name: "Happy Hollow Park", lat: 37.3193, lon: -121.8252, type: "park" },
    { name: "Almaden Lake Park", lat: 37.2660, lon: -121.8860, type: "splash" },
    { name: "San Jose Library",  lat: 37.3337, lon: -121.8907, type: "library" },
    { name: "Kelley Park",       lat: 37.3215, lon: -121.8503, type: "park" },
  ],
  Cupertino: [
    { name: "Memorial Park",    lat: 37.3230, lon: -122.0461, type: "park" },
    { name: "Cupertino Library",lat: 37.3225, lon: -122.0316, type: "library" },
    { name: "Creekside Park",   lat: 37.3159, lon: -122.0278, type: "park" },
  ],
  "Mountain View": [
    { name: "Rengstorff Park", lat: 37.4052, lon: -122.0885, type: "splash" },
    { name: "Shoreline Park",  lat: 37.4245, lon: -122.0826, type: "park" },
    { name: "MV Library",      lat: 37.3893, lon: -122.0806, type: "library" },
  ],
  "Palo Alto": [
    { name: "Magical Bridge",    lat: 37.4317, lon: -122.1129, type: "park" },
    { name: "Rinconada Pool",    lat: 37.4317, lon: -122.1149, type: "splash" },
    { name: "Palo Alto Library", lat: 37.4439, lon: -122.1602, type: "library" },
  ],
  Saratoga: [
    { name: "Congress Springs Park", lat: 37.2583, lon: -122.0238, type: "park" },
    { name: "Saratoga Library",      lat: 37.2637, lon: -122.0230, type: "library" },
  ],
};

export const CURATED = {
  indoor: [
    { id: "sunnyvale-lib",    name: "Sunnyvale Public Library",    free: true,
      image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Public+Library",
      description: "Story time, STEM kits and free kids events all summer long." },
    { id: "pump-it-up",       name: "Pump It Up Sunnyvale",        free: false,
      image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600",
      mapUrl: "https://www.google.com/maps/search/Pump+It+Up+Sunnyvale",
      description: "Giant inflatable bounce houses and slides for toddlers to teens!" },
    { id: "swim-class",       name: "City Swim Lessons",           free: false,
      image: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+swim+lessons+kids",
      description: "City-run swim lessons for all ages, infant through teen." },
    { id: "sports-indoor",    name: "Youth Indoor Sports Center",  free: false,
      image: "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=600",
      mapUrl: "https://www.google.com/maps/search/indoor+sports+kids+Sunnyvale",
      description: "Basketball, volleyball, and gymnastics for kids 0 to teen." },
    { id: "community-center", name: "Sunnyvale Community Center",  free: true,
      image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Community+Center",
      description: "Free drop-in activities, art classes, and family programs." },
    { id: "gymnastics-free",  name: "Free Open Gym at Rec Center", free: true,
      image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+recreation+center+gym",
      description: "Drop-in open gym hours for kids every weekday morning." },
    { id: "chess-club",       name: "Library Chess and Games Club",free: true,
      image: "https://images.unsplash.com/photo-1528819622765-d6bcf132f793?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Library",
      description: "Learn chess, board games, and puzzles every Saturday." },
    { id: "trampoline",       name: "Sky Zone Trampoline Park",    free: false,
      image: "https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=600",
      mapUrl: "https://www.google.com/maps/search/Sky+Zone+San+Jose",
      description: "Wall-to-wall trampolines, foam pits, and dodgeball arenas." },
    { id: "science-museum",   name: "Childrens Discovery Museum",  free: false,
      image: "https://images.unsplash.com/photo-1554757388-29a2a86ef02f?w=600",
      mapUrl: "https://www.google.com/maps/search/Childrens+Discovery+Museum+San+Jose",
      description: "Interactive science exhibits designed for kids 0 to 12." },
    { id: "indoor-climbing",  name: "Youth Rock Climbing",         free: false,
      image: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600",
      mapUrl: "https://www.google.com/maps/search/kids+rock+climbing+Sunnyvale",
      description: "Beginner walls to challenging routes, helmets included." },
  ],
  weekend: [
    { id: "ortega-park",    name: "Ortega Park",                 free: true,
      image: "https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=600",
      mapUrl: "https://www.google.com/maps/search/Ortega+Park+Sunnyvale",
      description: "Picnic areas, sports fields, and a great playground for all ages." },
    { id: "seven-seas",     name: "Seven Seas Park",             free: true,
      image: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=600",
      mapUrl: "https://www.google.com/maps/search/Seven+Seas+Park+Sunnyvale",
      description: "Splash pad water play and climbing structures for all ages." },
    { id: "baylands",       name: "Sunnyvale Baylands Park",     free: true,
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Baylands+Park",
      description: "Wide open trails, wetlands, and bird watching with the whole family." },
    { id: "magical-bridge", name: "Magical Bridge Playground",   free: true,
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
      mapUrl: "https://www.google.com/maps/search/Magical+Bridge+Playground+Palo+Alto",
      description: "Fully inclusive playground designed for kids of all abilities." },
    { id: "farmers-market", name: "Sunnyvale Farmers Market",    free: true,
      image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Farmers+Market",
      description: "Saturday morning fun with fresh food, live music, and kids activities." },
    { id: "las-palmas",     name: "Las Palmas Park",             free: true,
      image: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=600",
      mapUrl: "https://www.google.com/maps/search/Las+Palmas+Park+Sunnyvale",
      description: "Huge park with splash pad, tennis courts, and shaded picnic spots." },
    { id: "murphy-park",    name: "Murphy Park and Skate Plaza", free: true,
      image: "https://images.unsplash.com/photo-1520045892732-304bc3ac5d8e?w=600",
      mapUrl: "https://www.google.com/maps/search/Murphy+Park+Sunnyvale",
      description: "Skate plaza, basketball courts, and open green space for kids." },
    { id: "happy-hollow",   name: "Happy Hollow Park and Zoo",   free: false,
      image: "https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=600",
      mapUrl: "https://www.google.com/maps/search/Happy+Hollow+Park+Zoo+San+Jose",
      description: "A zoo, rides, and puppet theater designed just for young children." },
    { id: "shoreline",      name: "Shoreline Park Mountain View",free: true,
      image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600",
      mapUrl: "https://www.google.com/maps/search/Shoreline+Park+Mountain+View",
      description: "Kite flying, bike trails, and stunning bay views for the whole family." },
    { id: "creek-trail",    name: "Stevens Creek Trail",         free: true,
      image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600",
      mapUrl: "https://www.google.com/maps/search/Stevens+Creek+Trail",
      description: "Shaded 5-mile family biking and walking trail through the valley." },
  ],
  summer: [
    { id: "lib-summer",    name: "Library Summer Reading",       free: true,
      image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Public+Library",
      description: "Free summer reading challenge with prizes for kids 0 to teen!" },
    { id: "free-art",      name: "Free Art Classes",             free: true,
      image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Community+Center+art+classes",
      description: "Drop-in art sessions every Tuesday and Thursday, totally free." },
    { id: "splash-pad",    name: "Las Palmas Splash Pad",        free: true,
      image: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=600",
      mapUrl: "https://www.google.com/maps/search/Las+Palmas+Park+Sunnyvale",
      description: "Free splash pad open all summer, bring towels and sunscreen!" },
    { id: "hiking-trails", name: "Stevens Creek Trail Hiking",   free: true,
      image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600",
      mapUrl: "https://www.google.com/maps/search/Stevens+Creek+Trail+Sunnyvale",
      description: "Easy, shaded nature trail perfect for families with young kids." },
    { id: "free-movies",   name: "Free Movies in the Park",      free: true,
      image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+movies+in+the+park",
      description: "Bring a blanket and enjoy free family films at Murphy Park." },
    { id: "lib-stem",      name: "Library Free STEM Workshops",  free: true,
      image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Library",
      description: "Robotics, coding, and science workshops, free every Wednesday." },
    { id: "free-tennis",   name: "Free Junior Tennis Clinics",   free: true,
      image: "https://images.unsplash.com/photo-1551773188-0801da12ddae?w=600",
      mapUrl: "https://www.google.com/maps/search/tennis+courts+Sunnyvale",
      description: "Free beginner tennis clinics for kids 6 to 16 at city courts." },
    { id: "free-yoga",     name: "Family Yoga in the Park",      free: true,
      image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600",
      mapUrl: "https://www.google.com/maps/search/yoga+in+the+park+Sunnyvale",
      description: "Free Saturday morning family yoga at Ortega Park." },
    { id: "nature-walk",   name: "Guided Nature Walks for Kids", free: true,
      image: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Baylands+nature+walk",
      description: "Ranger-led nature walks at Baylands identifying birds and plants." },
    { id: "lib-crafts",    name: "Free Craft Days at Library",   free: true,
      image: "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=600",
      mapUrl: "https://www.google.com/maps/search/Sunnyvale+Library",
      description: "Weekly drop-in craft sessions for ages 3 to 12 with free supplies." },
  ],
  paid: [
    { id: "paid-swim",       name: "Private Swim Lessons",       free: false,
      image: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600",
      mapUrl: "https://www.google.com/maps/search/swim+lessons+Sunnyvale",
      description: "One-on-one swim instruction for infants through teens." },
    { id: "pump-paid",       name: "Pump It Up Open Jump",       free: false,
      image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600",
      mapUrl: "https://www.google.com/maps/search/Pump+It+Up+Sunnyvale",
      description: "Buy tickets for open jump sessions, endless bouncy fun!" },
    { id: "coding-camp",     name: "Kids Coding Workshop",       free: false,
      image: "https://images.unsplash.com/photo-1587620962725-abab19836100?w=600",
      mapUrl: "https://www.google.com/maps/search/kids+coding+camp+Sunnyvale",
      description: "Learn Scratch and Python in fun weekly classes for ages 6 to 14." },
    { id: "gymnastics",      name: "Youth Gymnastics Classes",   free: false,
      image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600",
      mapUrl: "https://www.google.com/maps/search/youth+gymnastics+Sunnyvale",
      description: "Beginner to advanced gymnastics for toddlers through teens." },
    { id: "martial-arts",    name: "Kids Martial Arts",          free: false,
      image: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=600",
      mapUrl: "https://www.google.com/maps/search/kids+martial+arts+Sunnyvale",
      description: "Fun, confidence-building karate and taekwondo for all ages." },
    { id: "soccer",          name: "Youth Soccer League",        free: false,
      image: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=600",
      mapUrl: "https://www.google.com/maps/search/youth+soccer+Sunnyvale",
      description: "Weekly games and skill clinics for kids ages 4 to 16." },
    { id: "dance",           name: "Kids Dance Classes",         free: false,
      image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600",
      mapUrl: "https://www.google.com/maps/search/kids+dance+class+Sunnyvale",
      description: "Ballet, hip-hop, and jazz dance for toddlers through teens." },
    { id: "art-studio",      name: "Youth Art Studio Classes",   free: false,
      image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600",
      mapUrl: "https://www.google.com/maps/search/kids+art+classes+Sunnyvale",
      description: "Painting, pottery, and mixed media in a creative studio setting." },
    { id: "rock-climbing-p", name: "Rock Climbing for Kids",     free: false,
      image: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600",
      mapUrl: "https://www.google.com/maps/search/rock+climbing+gym+kids+Sunnyvale",
      description: "Guided youth climbing sessions with certified instructors." },
    { id: "sky-zone",        name: "Sky Zone Trampoline Park",   free: false,
      image: "https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=600",
      mapUrl: "https://www.google.com/maps/search/Sky+Zone+San+Jose",
      description: "Wall-to-wall trampolines, foam pits, obstacle courses, and more." },
  ],
};
