// summerCamps.js
// Drop this into your SunScout/src/ folder (alongside activities.js, places.js, etc.)
// Each city shows ONLY its own activities — no cross-city bleed.

export const FREE_SUMMER_CAMPS = {
  Sunnyvale: [
    {
      id: "sv-free-1",
      city: "Sunnyvale",
      name: "Free Coding Class — Scratch & Python Intro",
      org: "Sunnyvale Public Library",
      category: "coding",
      tags: ["Ages 8–14", "Drop-in", "Every Saturday"],
      price: "FREE",
      dates: "Jun 7 – Aug 30, 2026",
      location: "665 W. Olive Ave, Sunnyvale",
      description:
        "Weekly drop-in coding classes at the Innovation Lab. Kids learn Scratch and Python basics with library staff. No registration required.",
      link: "https://www.library.sunnyvale.ca.gov/events/kids-events",
      badge: "free",
    },
    {
      id: "sv-free-2",
      city: "Sunnyvale",
      name: "Summer Reading Program — Kids (Ages 0–Grade 5)",
      org: "Sunnyvale Public Library",
      category: "library",
      tags: ["Ages 0–10", "Jun 1 – Aug 31", "Free book on sign-up"],
      price: "FREE",
      dates: "Jun 1 – Aug 31, 2026",
      location: "665 W. Olive Ave, Sunnyvale",
      description:
        "Free paperback book when you sign up. Track reading on Beanstack and earn prizes all summer long.",
      link: "https://www.library.sunnyvale.ca.gov/services/reading-programs",
      badge: "free",
    },
    {
      id: "sv-free-3",
      city: "Sunnyvale",
      name: "Summer Reading Program — Teens (Grades 6–12)",
      org: "Sunnyvale Public Library",
      category: "library",
      tags: ["Ages 11–18", "Jun 1 – Aug 31"],
      price: "FREE",
      dates: "Jun 1 – Aug 31, 2026",
      location: "665 W. Olive Ave, Sunnyvale",
      description:
        "Teen reading program with free book on sign-up. Earn rewards through August 31.",
      link: "https://www.library.sunnyvale.ca.gov/services/reading-programs",
      badge: "free",
    },
    {
      id: "sv-free-4",
      city: "Sunnyvale",
      name: "Free Storytime at the Library",
      org: "Sunnyvale Public Library",
      category: "storytime",
      tags: ["Ages 2–7", "Wednesdays 10am", "No sign-up"],
      price: "FREE",
      dates: "Jun – Aug 2026, Every Wednesday",
      location: "Children's Room, 665 W. Olive Ave, Sunnyvale",
      description:
        "Weekly interactive storytime with songs, puppets, and crafts for young children. Drop-in, no registration required.",
      link: "https://www.library.sunnyvale.ca.gov/events/kids-events",
      badge: "free",
    },
    {
      id: "sv-free-5",
      city: "Sunnyvale",
      name: "Egg Hunt & Spring Festival — Murphy Park",
      org: "City of Sunnyvale Parks & Recreation",
      category: "park",
      tags: ["All ages", "Murphy Park", "Seasonal"],
      price: "FREE",
      dates: "Summer 2026 — Baylands & Murphy Park",
      location: "Murphy Ave & Sunnyvale Ave, Sunnyvale",
      description:
        "Free seasonal community events at Sunnyvale parks — egg hunts, nature scavenger hunts, and outdoor family activities.",
      link: "https://www.sunnyvale.ca.gov/recreation-and-community",
      badge: "free",
    },
    {
      id: "sv-free-6",
      city: "Sunnyvale",
      name: "Free Swimming Lessons — Las Palmas Aquatic Center",
      org: "City of Sunnyvale Recreation",
      category: "swimming",
      tags: ["Ages 4+", "Session-based", "Registration required"],
      price: "FREE / Low-cost",
      dates: "Jun – Aug 2026",
      location: "850 Russet Dr, Sunnyvale (Las Palmas Park)",
      description:
        "City-subsidized beginner swim lessons at Las Palmas Aquatic Center. Register early — spots fill fast.",
      link: "https://registration.sunnyvale.ca.gov/webtrac/web/search.html",
      badge: "free",
    },
    {
      id: "sv-free-7",
      city: "Sunnyvale",
      name: "STEM Reading Kick-Off — Crafts & Scavenger Hunt",
      org: "Sunnyvale Public Library",
      category: "stem",
      tags: ["All ages", "One-day event", "No registration"],
      price: "FREE",
      dates: "Early June 2026 (exact date TBA)",
      location: "Sunnyvale Public Library, 665 W. Olive Ave",
      description:
        "Summer kick-off event with crafts, games, scavenger hunt, and special guest storytime. Open to all ages.",
      link: "https://www.library.sunnyvale.ca.gov/events/kids-events",
      badge: "free",
    },
    {
      id: "sv-free-8",
      city: "Sunnyvale",
      name: "3D Printing & Innovation Lab Drop-In",
      org: "Sunnyvale Public Library",
      category: "coding",
      tags: ["Ages 10+", "Drop-in", "Innovation Lab"],
      price: "FREE",
      dates: "Year-round, Mon–Thu 10am–9pm",
      location: "Innovation Lab, 665 W. Olive Ave, Sunnyvale",
      description:
        "Free access to 3D printers, coding stations, and laser cutters. Library card required. Staff-assisted intro workshops available.",
      link: "https://www.library.sunnyvale.ca.gov/services",
      badge: "free",
    },
  ],

  "Santa Clara": [
    {
      id: "sc-free-1",
      city: "Santa Clara",
      name: "Santa Clara City Library Summer Reading",
      org: "Santa Clara City Library",
      category: "library",
      tags: ["All ages", "Jun–Aug"],
      price: "FREE",
      dates: "Jun 1 – Aug 31, 2026",
      location: "2635 Homestead Rd, Santa Clara",
      description:
        "Free summer reading with prizes and events for all ages at the Santa Clara City Library.",
      link: "https://www.sclibrary.org/",
      badge: "free",
    },
    {
      id: "sc-free-2",
      city: "Santa Clara",
      name: "Kids Coding Storytime",
      org: "Santa Clara City Library",
      category: "coding",
      tags: ["Ages 5–10", "Weekly"],
      price: "FREE",
      dates: "Jun – Aug 2026",
      location: "2635 Homestead Rd, Santa Clara",
      description:
        "Weekly coding stories and activities introducing programming concepts through books and games.",
      link: "https://www.sclibrary.org/",
      badge: "free",
    },
  ],

  "Mountain View": [
    {
      id: "mv-free-1",
      city: "Mountain View",
      name: "Mountain View Library Summer Kids Events",
      org: "Mountain View Public Library",
      category: "library",
      tags: ["Kids & Teens", "Jun–Aug"],
      price: "FREE",
      dates: "Jun – Aug 2026",
      location: "585 Franklin St, Mountain View",
      description:
        "Free summer programming — science demos, crafts, and reading challenges for all ages.",
      link: "https://www.mountainview.gov/depts/library/default.asp",
      badge: "free",
    },
    {
      id: "mv-free-2",
      city: "Mountain View",
      name: "Outdoor Movie & Family Nights — Rengstorff Park",
      org: "Mountain View Parks & Recreation",
      category: "park",
      tags: ["All ages", "Evenings"],
      price: "FREE",
      dates: "Jul – Aug 2026",
      location: "Rengstorff Park, Mountain View",
      description:
        "Free outdoor family movie nights at Rengstorff Park. Bring blankets and snacks.",
      link: "https://www.mountainview.gov/depts/cs/recreation/default.asp",
      badge: "free",
    },
  ],

  "San Jose": [
    {
      id: "sj-free-1",
      city: "San Jose",
      name: "San Jose Public Library Summer Reading",
      org: "San Jose Public Library",
      category: "library",
      tags: ["All ages", "Jun–Aug", "All branches"],
      price: "FREE",
      dates: "Jun 1 – Aug 31, 2026",
      location: "All SJPL branches, San Jose",
      description:
        "City-wide free reading program with prizes, events, and STEM activities at all branch libraries.",
      link: "https://www.sjpl.org/",
      badge: "free",
    },
    {
      id: "sj-free-2",
      city: "San Jose",
      name: "Free Swimming Lessons — Almaden & Hoover Pools",
      org: "City of San Jose Parks",
      category: "swimming",
      tags: ["Ages 4+", "Session-based"],
      price: "FREE / Low-cost",
      dates: "Jun – Aug 2026",
      location: "Multiple pools, San Jose",
      description:
        "Subsidized beginner swim lessons at city aquatic centers. Register at sanjoseca.gov.",
      link: "https://www.sanjoseca.gov/your-government/departments/parks-recreation-neighborhood-services",
      badge: "free",
    },
  ],

  Cupertino: [
    {
      id: "cu-free-1",
      city: "Cupertino",
      name: "Cupertino Library Kids Summer Activities",
      org: "Cupertino Library",
      category: "library",
      tags: ["Kids & Teens", "Jun–Aug"],
      price: "FREE",
      dates: "Jun – Aug 2026",
      location: "10800 Torre Ave, Cupertino",
      description:
        "Free summer events, STEM workshops, and reading programs at the Cupertino Branch Library.",
      link: "https://www.sccl.org/cupertino",
      badge: "free",
    },
  ],
};

export const PAID_SUMMER_CAMPS = {
  Sunnyvale: [
    {
      id: "sv-paid-1",
      city: "Sunnyvale",
      name: "Camp Galileo — STEAM & Outdoor Adventures",
      org: "Galileo Camps",
      category: "stem",
      tags: ["K–Grade 10", "$499/week", "9am–3pm"],
      price: "From $499/week",
      dates: "Jun – Aug 2026",
      location: "Sunnyvale campus (see site for address)",
      description:
        "STEAM projects, outdoor play, art and group challenges. Early-bird $50 off. Extended care 8am–6pm available.",
      link: "https://galileo-camps.com/our-camps/locations/sunnyvale/",
      badge: "sponsored",
    },
    {
      id: "sv-paid-2",
      city: "Sunnyvale",
      name: "Integem AI, Robotics & Drones Camp",
      org: "Integem",
      category: "coding",
      tags: ["Ages 5–18", "NVIDIA-partnered", "Use code FUN26"],
      price: "Use code FUN26 to save",
      dates: "Jun – Aug 2026",
      location: "Multiple South Bay locations",
      description:
        "AR coding, 3D design, AI & robotics. ACS WASC accredited. Beginner to advanced. Use FUN26 to save.",
      link: "https://camp.integem.com",
      badge: null,
    },
    {
      id: "sv-paid-3",
      city: "Sunnyvale",
      name: "Sunnyvale Swim Club — Summer Splash",
      org: "SUNN Swim Club",
      category: "swimming",
      tags: ["Ages 8+", "Competitive prep", "$675 + $56 USA fee"],
      price: "$675 + $56 USA Swimming fee",
      dates: "Summer 2026",
      location: "Sunnyvale Aquatic Center",
      description:
        "Competitive swim training for kids ready to join a team. Covers all four strokes, body position and race prep.",
      link: "https://www.sunn.org/page/programs/summer-splash",
      badge: null,
    },
    {
      id: "sv-paid-4",
      city: "Sunnyvale",
      name: "SVCM Music Summer Camp",
      org: "Silicon Valley Conservatory of Music",
      category: "arts",
      tags: ["Ages 5–11", "9am–3pm", "DIY Ukulele take-home"],
      price: "See svcm.us.com for pricing",
      dates: "Multiple sessions, Jun – Aug 2026",
      location: "Sunnyvale campus",
      description:
        "10-day music camp with Disney, Forest, Ocean & Animal themes. Kids take home a DIY ukulele and perform at a farewell recital.",
      link: "http://svcm.us.com/summer",
      badge: null,
    },
    {
      id: "sv-paid-5",
      city: "Sunnyvale",
      name: "FASSV French-English Immersion Camp",
      org: "French American School of Silicon Valley",
      category: "arts",
      tags: ["Ages 3–Grade 5", "Bilingual", "Jun 15 – Jul"],
      price: "See site for pricing",
      dates: "Session 1: Jun 15–19, 2026",
      location: "FASSV Campus, Sunnyvale",
      description:
        "Non-academic bilingual summer fun. No French required. Small 10:1 ratio groups. Nurturing, language-rich environment.",
      link: "https://www.fassv.org/after-school/summer-camp.cfm",
      badge: null,
    },
    {
      id: "sv-paid-6",
      city: "Sunnyvale",
      name: "Lifetime Activities — Tennis, Chess & Combo Camps",
      org: "Lifetime Activities",
      category: "sports",
      tags: ["Kids & Teens", "25+ years", "Multiple sports"],
      price: "See site for pricing",
      dates: "Jun – Aug 2026",
      location: "Sunnyvale location (see site)",
      description:
        "Tennis, badminton, chess, volleyball, table tennis, pickleball and combo camps. 25+ years of Bay Area summer camps.",
      link: "https://www.lifetimeactivities.com/",
      badge: null,
    },
    {
      id: "sv-paid-7",
      city: "Sunnyvale",
      name: "Brains & Motion STEM Summer Camp",
      org: "Brains & Motion Education",
      category: "stem",
      tags: ["K–Grade 8", "Enrichment", "Full-day"],
      price: "See site for pricing",
      dates: "Jun – Aug 2026",
      location: "Sunnyvale campus",
      description:
        "Premier STEM summer camp blending education and adventure. Hands-on science and engineering projects for K–8.",
      link: "https://www.brainsandmotion.com/",
      badge: null,
    },
  ],

  "Menlo Park": [
    {
      id: "mp-paid-1",
      city: "Menlo Park",
      name: "Coding & Robotics Camp",
      org: "CodeLinkd",
      category: "coding",
      tags: ["Ages 7–14", "May 25–Sep 7", "Hands-on"],
      price: "See ActivityHero for pricing",
      dates: "May 25 – Sep 7, 2026",
      location: "Menlo Park, CA",
      description:
        "Hands-on coding and robotics for ages 7–14. Book directly through ActivityHero.",
      link: "https://www.activityhero.com/biz/codelinkd/coding-robotics?geo=menlo-park-ca&location_id=166550&activity_schedule_id=1920069&start_date=2026-05-25&end_date=2026-09-07",
      badge: "sponsored",
    },
  ],

  "Santa Clara": [
    {
      id: "sc-paid-1",
      city: "Santa Clara",
      name: "iD Tech Camps — Coding, Game Dev & Robotics",
      org: "iD Tech",
      category: "coding",
      tags: ["Ages 7–17", "Week-long", "University campus"],
      price: "From $849/week",
      dates: "Jun – Aug 2026",
      location: "Santa Clara University campus",
      description:
        "Coding, Minecraft modding, game design & robotics. The world's #1 tech camp for 23+ years.",
      link: "https://www.idtech.com/",
      badge: null,
    },
    {
      id: "sc-paid-2",
      city: "Santa Clara",
      name: "Gymnastics & Ninja Day Camp",
      org: "California Sports Center",
      category: "sports",
      tags: ["Ages 3–16", "Mid-Jun to Mid-Aug", "Water play"],
      price: "See site for pricing",
      dates: "Mid-Jun – Mid-Aug 2026",
      location: "California Sports Center, Santa Clara",
      description:
        "Week-long camps with gymnastics, ninja, or dance. Exciting themes, crafts, and outdoor water play every day.",
      link: "https://www.californiasc.com/",
      badge: null,
    },
  ],

  "Mountain View": [
    {
      id: "mv-paid-1",
      city: "Mountain View",
      name: "Camp Galileo — STEAM Adventures",
      org: "Galileo Camps",
      category: "stem",
      tags: ["K–Grade 10", "$499/week", "Extended care"],
      price: "From $499/week",
      dates: "Jun – Aug 2026",
      location: "Mountain View campus",
      description:
        "Same acclaimed STEAM + outdoor adventure program at the Mountain View campus.",
      link: "https://galileo-camps.com/",
      badge: "sponsored",
    },
    {
      id: "mv-paid-2",
      city: "Mountain View",
      name: "Advanced Art Camps",
      org: "Art School of SF Bay",
      category: "arts",
      tags: ["Kids & Teens", "Portfolio prep", "Professional artists"],
      price: "See site for pricing",
      dates: "Jun – Aug 2026",
      location: "Mountain View campus",
      description:
        "Drawing, painting, watercolor, digital art and animation. Skill-building camps led by professional artists.",
      link: "https://www.artschoolsfbay.com/camps",
      badge: null,
    },
  ],

  "Palo Alto": [
    {
      id: "pa-paid-1",
      city: "Palo Alto",
      name: "BrainVyne LEGO & Robotics Camp",
      org: "BrainVyne",
      category: "coding",
      tags: ["Ages 4–14", "Engineering through play"],
      price: "See site for pricing",
      dates: "Jun – Aug 2026",
      location: "Palo Alto / Menlo Park",
      description:
        "LEGO gears, axles & robotics for ages 4–14. From Bricks for Tots to Girl Power Robotics camps.",
      link: "https://www.brainvyne.com/",
      badge: null,
    },
    {
      id: "pa-paid-2",
      city: "Palo Alto",
      name: "CodeREV STEAM Camp — Coding, Game Design & Animation",
      org: "CodeREV Kids",
      category: "coding",
      tags: ["Ages 6–15", "In-person", "Expert instructors"],
      price: "See site for pricing",
      dates: "Jun – Aug 2026",
      location: "Los Altos / Palo Alto",
      description:
        "Coding, STEAM, game design, robotics, engineering and animation. Expert instructors with outdoor activities too.",
      link: "https://www.coderevkids.com/",
      badge: null,
    },
  ],

  "San Jose": [
    {
      id: "sj-paid-1",
      city: "San Jose",
      name: "Club SciKidz Robot Engineering Camp",
      org: "Club SciKidz Silicon Valley",
      category: "stem",
      tags: ["Ages 6–12", "60+ STEM themes", "Week-long"],
      price: "See site for pricing",
      dates: "Jun 22 – Aug 2026 (multiple sessions)",
      location: "Multiple San Jose venues",
      description:
        "60+ themed science camps — robotics, forensics, game design, veterinary medicine, space and more.",
      link: "https://siliconvalley.clubscikidz.com/",
      badge: null,
    },
  ],
};

// Helper: get all cities that have data
export const CAMP_CITIES = {
  free: Object.keys(FREE_SUMMER_CAMPS),
  paid: Object.keys(PAID_SUMMER_CAMPS),
};